### ISSUE TITLE
Generation for readthedocs needs to be updated

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#112]
Currently, the generation of documentation at readthedocs fails. The site has updated and asks for a different file structure than what we currently offer. As a result, we get:

![image](https://github.com/averbraeck/opentrafficsim/assets/13779793/59882926-3e67-46db-8c68-e8dc3a38c319)

**Comment by averbraeck** [comment]
A new config file named `.readthedocs.yaml` needs to be added in the root of the project. 

See https://docs.readthedocs.io/en/stable/config-file/index.html for more details.

**Comment by averbraeck** [comment]
The `mkdocs.yml` file can be moved to the `docs` folder to keep the root folder as clean as possible.
The same holds for the `requirements.txt` file.

The `.readthedocs.yaml` file then looks as follows:

```yaml
# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: docs/mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: docs/requirements.txt
```
